### ISSUE TITLE
TODO: spell casting

### ISSUE THREAD

**Issue by Xiaoy312** [Xiaoy312/Xy.PerfectWorld#2]
- [x] analyse Skill structure
- [x] find call for Casting
- [x] make Casting call
- [ ] add new fighting strategy :
  - [X] Basic : spam basic attack
  - [x] Boss Killer : spam basic attack, and use spark as it becomes available
  - [ ] SpellCaster : spam primary skills to on cd & w/enough chi, and a list of fillers(or autos) to cast when none of primary skills are on cd
